// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVntfMC44DivXY0szwEMfyv1HXqXspe54',
    appId: '1:671800418110:web:9348ebefed55d26d08566f',
    messagingSenderId: '671800418110',
    projectId: 'auth-login-ui',
    authDomain: 'auth-login-ui.firebaseapp.com',
    storageBucket: 'auth-login-ui.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAz16thDdMJzN_v24PB1_Oa90Qx4EgJmg',
    appId: '1:671800418110:android:9bd4fc8f9513f00c08566f',
    messagingSenderId: '671800418110',
    projectId: 'auth-login-ui',
    storageBucket: 'auth-login-ui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXqsc4_kbUhVWb6v1OH2GXN8xaYU6r6Bo',
    appId: '1:671800418110:ios:97b6f2e6ecfceb1408566f',
    messagingSenderId: '671800418110',
    projectId: 'auth-login-ui',
    storageBucket: 'auth-login-ui.appspot.com',
    iosClientId: '671800418110-ialo19rl0qdntmr42iv4g32t7ca1aj1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.apptest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXqsc4_kbUhVWb6v1OH2GXN8xaYU6r6Bo',
    appId: '1:671800418110:ios:441440458df0ae2a08566f',
    messagingSenderId: '671800418110',
    projectId: 'auth-login-ui',
    storageBucket: 'auth-login-ui.appspot.com',
    iosClientId: '671800418110-dbfm7ru0b9t1fu04naoa2jlbivqqgdfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.apptest.RunnerTests',
  );
}
